---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: word-service
  namespace: default
  labels:
    app: word-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: word-service
  template:
    metadata:
      labels:
        app: word-service
    spec:
      containers:
        - name: word-service
          image: motus/word-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8083
          env:
            - name: DB_HOST
              value: postgres-service
            - name: DB_NAME
              value: db_words
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            initialDelaySeconds: 40
            periodSeconds: 10
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            initialDelaySeconds: 60
            periodSeconds: 15
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: word-service
  namespace: default
spec:
  selector:
    app: word-service
  ports:
    - port: 8083
      targetPort: 8083
  type: ClusterIP
